services:

  app:
    build:
      context: ./app
    stop_signal: SIGKILL
    ports:
      - 8080:8080
    environment:
      FLASK_APP: main.py
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    build: .
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - log_destination=stderr
      - logging_collector=on
      - log_directory='/var/log/postgresql'
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./logs/:/var/log/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge



